platform :ios, ‘8.0’

target 'sunduskCamera' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for sunduskCamera

  target 'sunduskCameraTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sunduskCameraUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod ‘GPUImage’

end
